# Generated by Django 5.2.10 on 2026-06-04 16:50

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon identifier e.g. lightning, target, fire",
                        max_length=50,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        help_text='JSON criteria for auto-awarding, e.g. {"type":"modules_per_day","threshold":3}'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "achievements",
            },
        ),
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("problem_statement", models.TextField()),
                ("starter_code", models.TextField(blank=True, default="")),
                ("reference_solution", models.TextField(blank=True, default="")),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python")], default="python", max_length=20
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("intermediate", "Intermediate"),
                            ("difficult", "Difficult"),
                        ],
                        default="intermediate",
                        max_length=15,
                    ),
                ),
                ("constraints", models.JSONField(blank=True, default=dict)),
                ("hints", models.JSONField(blank=True, default=list)),
                ("is_generated", models.BooleanField(default=False)),
                (
                    "generation_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "coding_problems",
            },
        ),
        migrations.CreateModel(
            name="CoursePlanningTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_title",
                    models.CharField(
                        help_text="Title of the course/topic to plan", max_length=255
                    ),
                ),
                (
                    "course_description",
                    models.TextField(help_text="Description of what should be covered"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web_dev", "Web Development"),
                            ("data_science", "Data Science"),
                            ("ai_ml", "AI & Machine Learning"),
                            ("mobile_dev", "Mobile Development"),
                            ("cloud", "Cloud Computing"),
                            ("design", "Design"),
                            ("devops", "DevOps"),
                            ("cybersecurity", "Cybersecurity"),
                            ("blockchain", "Blockchain"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "thumbnail",
                    models.URLField(
                        blank=True, default="", help_text="URL to course thumbnail"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("progress_message", models.TextField(blank=True, default="")),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        help_text="Complete course plan result from LLM (is_broad, courses, etc.)",
                        null=True,
                    ),
                ),
                (
                    "created_courses",
                    models.JSONField(
                        blank=True,
                        help_text="IDs of courses created from this plan",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "course_planning_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated lesson content (Markdown/HTML)",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_push", models.BooleanField(default=True)),
                ("notify_course_updates", models.BooleanField(default=False)),
                ("language", models.CharField(default="en", max_length=20)),
                ("theme", models.CharField(default="light", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python")], default="python", max_length=20
                    ),
                ),
                ("source_code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "score_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("passed_tests", models.PositiveSmallIntegerField(default=0)),
                ("total_tests", models.PositiveSmallIntegerField(default=0)),
                ("feedback", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="api.codingproblem",
                    ),
                ),
            ],
            options={
                "db_table": "code_submissions",
            },
        ),
        migrations.CreateModel(
            name="CodeExecutionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("progress_message", models.TextField(blank=True, default="")),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_task",
                        to="api.codesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "code_execution_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(db_index=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web_dev", "Web Development"),
                            ("data_science", "Data Science"),
                            ("ai_ml", "AI & Machine Learning"),
                            ("mobile_dev", "Mobile Development"),
                            ("cloud", "Cloud Computing"),
                            ("design", "Design"),
                            ("devops", "DevOps"),
                            ("cybersecurity", "Cybersecurity"),
                            ("blockchain", "Blockchain"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "thumbnail",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to course thumbnail image",
                    ),
                ),
                ("is_popular", models.BooleanField(db_index=True, default=False)),
                (
                    "is_sub_topic",
                    models.BooleanField(
                        default=True,
                        help_text="True if this is a learnable sub-topic, False if broad topic category",
                    ),
                ),
                (
                    "parent_topic_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Name of the broad topic this sub-topic belongs to (e.g., "AI & Machine Learning")',
                        max_length=255,
                    ),
                ),
                (
                    "prerequisites",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of prerequisite sub-topic names or IDs",
                    ),
                ),
                (
                    "learning_objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of specific learning objectives for this sub-topic",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this course",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coding_problems",
                to="api.course",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_style_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mindmap", "Mind Map"),
                            ("videos", "Videos"),
                            ("summary", "Summary Notes"),
                            ("books", "Books"),
                            ("reels", "Short Reels"),
                        ],
                        default="",
                        help_text="Per-course learning style override",
                        max_length=20,
                    ),
                ),
                (
                    "diagnosed_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Level determined by diagnostic assessment",
                        max_length=15,
                    ),
                ),
                (
                    "study_method_preference",
                    models.CharField(
                        choices=[
                            ("real_world", "Real-world Examples"),
                            ("theory_depth", "Theory Depth"),
                            ("project_based", "Project-Based"),
                            ("custom", "Custom"),
                        ],
                        default="real_world",
                        help_text="How the student prefers to learn (affects syllabus generation)",
                        max_length=20,
                    ),
                ),
                (
                    "custom_study_method",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Custom study method description when study_method_preference is "custom"',
                    ),
                ),
                (
                    "ai_system_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated system prompt personalized to the user's learning style for this enrollment. Used as the LLM system instruction for notes and audio generation (not quiz).",
                    ),
                ),
                (
                    "assessment_questions_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of questions in the pre-knowledge assessment (determined by LLM based on complexity)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "overall_progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage 0.00–100.00",
                        max_digits=5,
                    ),
                ),
                ("total_study_time_minutes", models.PositiveIntegerField(default=0)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="api.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
            },
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_submissions",
                to="api.enrollment",
            ),
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        help_text="Whether this is a user message or assistant response",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="The actual message content")),
                (
                    "topic_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: Which topic was being discussed",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="The enrollment this chat message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="api.enrollment",
                    ),
                ),
            ],
            options={
                "db_table": "chat_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningProfile",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_style",
                    models.CharField(
                        choices=[
                            ("mindmap", "Mind Map"),
                            ("videos", "Videos"),
                            ("summary", "Summary Notes"),
                            ("books", "Books"),
                            ("reels", "Short Reels"),
                        ],
                        default="summary",
                        max_length=20,
                    ),
                ),
                (
                    "depth_preference",
                    models.CharField(
                        choices=[("surface", "Surface"), ("deep", "Deep")],
                        default="deep",
                        max_length=10,
                    ),
                ),
                (
                    "pace_preference",
                    models.CharField(
                        choices=[
                            ("slow", "Slow"),
                            ("moderate", "Moderate"),
                            ("fast", "Fast"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "quiz_preference",
                    models.BooleanField(
                        default=True, help_text="Whether user prefers frequent quizzes"
                    ),
                ),
                (
                    "attention_span_minutes",
                    models.PositiveIntegerField(
                        default=25, help_text="Estimated attention span in minutes"
                    ),
                ),
                (
                    "podcast_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable audio podcast generation for topics",
                    ),
                ),
                (
                    "podcast_auto_generate",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically generate podcasts for new topics",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "learning_profiles",
            },
        ),
        migrations.CreateModel(
            name="LearningRoadmap",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Increments when roadmap is refined after quiz",
                    ),
                ),
                (
                    "roadmap_data",
                    models.JSONField(
                        help_text='Full roadmap JSON: {"topics": [{"topic_name": "", "level": ""}]}'
                    ),
                ),
                (
                    "generated_by_model",
                    models.CharField(
                        default="llama3:8b-instruct-q4_K_M", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to="api.enrollment",
                    ),
                ),
            ],
            options={
                "db_table": "learning_roadmaps",
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coding_problems",
                to="api.lesson",
            ),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progresses",
                        to="api.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="api.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_progress",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Position in the course sequence"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=15,
                    ),
                ),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "is_generated",
                    models.BooleanField(
                        default=False, help_text="True if AI-generated from roadmap"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="api.course",
                    ),
                ),
            ],
            options={
                "db_table": "modules",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="api.module",
            ),
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coding_problems",
                to="api.module",
            ),
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="locked",
                        max_length=15,
                    ),
                ),
                (
                    "progress_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_minutes", models.PositiveIntegerField(default=0)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progresses",
                        to="api.enrollment",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="api.module",
                    ),
                ),
            ],
            options={
                "db_table": "module_progress",
            },
        ),
        migrations.CreateModel(
            name="PersonalizedSyllabus",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "syllabus_data",
                    models.JSONField(
                        help_text="Full personalized syllabus JSON with modules and topics"
                    ),
                ),
                (
                    "generated_by_model",
                    models.CharField(default="phi3:mini", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus",
                        to="api.enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personalized syllabi",
                "db_table": "personalized_syllabi",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("diagnostic", "Diagnostic Assessment"),
                            ("topic_quiz", "Topic Quiz"),
                            ("final_quiz", "Final Quiz"),
                            ("code_problem", "Code Problem"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("intermediate", "Intermediate"),
                            ("difficult", "Difficult"),
                        ],
                        max_length=15,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "options",
                    models.JSONField(
                        help_text='List of option strings, e.g. ["A","B","C","D"]'
                    ),
                ),
                (
                    "correct_answer_index",
                    models.PositiveSmallIntegerField(
                        help_text="0-based index into options list"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation of correct answer",
                    ),
                ),
                ("is_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for diagnostic questions, set for topic/final quizzes",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.module",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("diagnostic", "Diagnostic Assessment"),
                            ("topic_quiz", "Topic Quiz"),
                            ("final_quiz", "Final Quiz"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "score_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_questions", models.PositiveSmallIntegerField(default=0)),
                ("correct_answers", models.PositiveSmallIntegerField(default=0)),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "weak_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of weak area strings from AI evaluation",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="api.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for topic quizzes to identify specific topic/lesson",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="api.lesson",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for topic quizzes, null for diagnostic",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="api.module",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_attempts",
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option_index",
                    models.SmallIntegerField(
                        blank=True, help_text="Null if user skipped", null=True
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "response_time_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="api.question",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.quizattempt",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_answers",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("notes", "Summary Notes"),
                            ("pdf", "PDF Document"),
                            ("ppt", "Presentation"),
                            ("mindmap", "Mind Map"),
                            ("video_script", "Video Script (JSON)"),
                            ("video", "Video (MP4)"),
                            ("audio", "Audio/Podcast (MP3)"),
                            ("image", "Image (PNG)"),
                            ("reel", "Short Reel"),
                            ("code_exercise", "Code Exercise"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Text content (for notes, scripts, mindmap data)",
                    ),
                ),
                (
                    "content_json",
                    models.JSONField(
                        blank=True,
                        help_text="Structured content (video scripts with scenes, mindmap nodes)",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="For binary files: PDFs, PPTs, videos, audio, images",
                        null=True,
                        upload_to="resources/%Y/%m/",
                    ),
                ),
                ("file_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="For audio/video resources", null=True
                    ),
                ),
                ("is_generated", models.BooleanField(default=False)),
                (
                    "generation_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. llama3:8b-instruct-q4_K_M, stable-diffusion-v1-5",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="api.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "resources",
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="api.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_achievements",
            },
        ),
        migrations.CreateModel(
            name="VideoTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("progress_message", models.TextField(blank=True, default="")),
                (
                    "script_data",
                    models.JSONField(
                        blank=True,
                        help_text="Generated script JSON from Ollama",
                        null=True,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Final generated video file",
                        null=True,
                        upload_to="videos/",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a lesson",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_tasks",
                        to="api.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "video_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("module_completed", "Module Completed"),
                            ("course_started", "Course Started"),
                            ("assessment_passed", "Assessment Passed"),
                            ("quiz_completed", "Quiz Completed"),
                            ("achievement_earned", "Achievement Earned"),
                            ("course_completed", "Course Completed"),
                        ],
                        max_length=25,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text='Extra context e.g. {"score": 85, "course_id": 1}',
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_lo_user_id_b8c999_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodingTestCase",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(blank=True, default="")),
                ("expected_output", models.TextField(blank=True, default="")),
                ("explanation", models.TextField(blank=True, default="")),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="api.codingproblem",
                    ),
                ),
            ],
            options={
                "db_table": "coding_test_cases",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["problem", "is_hidden"],
                        name="coding_test_problem_375fc3_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["category", "is_popular"], name="courses_categor_fa7dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["-created_at"], name="courses_created_c00611_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["user", "status"], name="enrollments_user_id_b5f69f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "course")},
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["user", "-submitted_at"], name="code_submis_user_id_77e903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["problem", "-submitted_at"],
                name="code_submis_problem_028ac5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["enrollment", "-submitted_at"],
                name="code_submis_enrollm_27cc9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chathistory",
            index=models.Index(
                fields=["enrollment", "created_at"],
                name="chat_histor_enrollm_27b2a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningroadmap",
            index=models.Index(
                fields=["enrollment", "is_active"],
                name="learning_ro_enrollm_1ea467_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["enrollment", "is_completed"],
                name="lesson_prog_enrollm_9b2eb0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("enrollment", "lesson")},
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("course", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("module", "order")},
        ),
        migrations.AddIndex(
            model_name="codingproblem",
            index=models.Index(
                fields=["course", "language"], name="coding_prob_course__a9ec5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingproblem",
            index=models.Index(
                fields=["lesson", "-created_at"], name="coding_prob_lesson__7beb8c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moduleprogress",
            unique_together={("enrollment", "module")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["course", "question_type"], name="questions_course__0b1be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["module", "question_type"], name="questions_module__1b61ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["enrollment", "attempt_type"],
                name="quiz_attemp_enrollm_a7aca1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizanswer",
            unique_together={("attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["lesson", "resource_type"], name="resources_lesson__27467c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
    ]
