# Generated by Django 5.2.10 on 2026-06-20 10:07

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz Generation"),
                            ("video_generation", "Video Generation"),
                            ("mindmap", "Mind Map Generation"),
                            ("chat", "Chat / Q&A"),
                            ("coding", "Coding Problem"),
                            ("notes", "Notes Generation"),
                            ("podcast", "Podcast Generation"),
                            ("assessment", "Assessment"),
                            ("course_planning", "Course Planning"),
                            ("remediation", "Remediation Content"),
                            ("dynamic_script", "Dynamic Script"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of prompt/input tokens consumed"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of completion/output tokens generated",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="LLM model name (e.g. claude-3-5-sonnet, gpt-4o)",
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text='Extra context e.g. {"course_id": 1, "enrollment_id": 2}',
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the AI call (null for system calls)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "token_usage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type"],
                        name="token_usage_user_id_297c67_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="token_usage_activit_d34d4a_idx",
                    ),
                ],
            },
        ),
    ]
